### ISSUE TITLE
API is useless for 1.17 lunar

### ISSUE THREAD

**Issue by LaserSlime** [LunarClient/BukkitAPI#18]
The api works fine for the 1.16 version of lunar client for me, but if i use 1.17 disabling mods doesn't work and setting waypoints doesn't seem to work either. I tried both 1.16 server with viaversion and a native 1.17 server. I also tried using both the implementation and the api directly. Issue always persisted.

**Comment by GamerRealm** [comment]
Vouch.

Tbh the API works fine only on 1.7 & 1.8 from my own testing.
On higher versions it works but it still has issues like x-ray mod & lunar cooldowns.

**Comment by LaserSlime** [comment]
Tried to use the api again. This time the client says that the modules got disabled, but they can still be enabled. Definitely a client issue.

**Comment by LaserSlime** [comment]
Seems to be fixed now.
