### ISSUE TITLE
force-disabled-mods not working with LunarClient API

### ISSUE THREAD

**Issue by Pantera07** [LunarClient/BukkitAPI#29]
force-disabled-mods will not work.
The mod disable works the first time the player turns on the client and enters it.
If the player leaves and re-enters the server, the mod disable will not work.
Disabled is displayed in the upper right corner. However, it is not actually disabled.
This is a client side issue.
Please fix.

https://github.com/LunarClient/BukkitAPI/releases/
https://github.com/LunarClient/BukkitImpl/releases/
![3](https://user-images.githubusercontent.com/89838384/153120611-f0f1087b-bb4f-40e8-a9ae-08c0e86d5015.png)

LunarClient Support Ticket ↓
![1](https://user-images.githubusercontent.com/89838384/153120533-f5423778-bd90-4474-886f-27c802dd6bb2.png)

**Comment by Pantera07** [comment]
https://github.com/LunarClient/BukkitImpl/issues/12

**Comment by phase** [comment]
Thank you for this report! We believe we have a fix that will be deployed soon.

**Comment by Pantera07** [comment]
> Thank you for this report! We believe we have a fix that will be deployed soon.

I believe this will be fixed soon. :)

**Comment by jakeman5** [comment]
Any progress on this. My whole community isn't able to use Lunar as of now because of this.

**Comment by timof121** [comment]
cool fix

**Comment by SirvydasS** [comment]
Can't reproduce. force-disabled-mods working.
And I have a question, how do know what mod title to write in config to disable that mod? For example, I want to disable Day Counter mod. Maybe is there any list for that (in config is an old list)? Because I can't test several modes. 
![image](https://user-images.githubusercontent.com/8950371/155272139-4f1c4819-5aae-4f06-8157-f2ee9422adef.png)

**Comment by Pantera07** [comment]
This bug has been fixed.

**Comment by Budderman18** [comment]
bug re-appearing

**Comment by LaserSlime** [comment]
It seems like now it's the other way around. It doesn't work when you join for the first time, but once you rejoin it works.
