### ISSUE TITLE
tnt countdown

### ISSUE THREAD

**Issue by BebeDlaStreat** [LunarClient/BukkitAPI#35]
Hello,
I would like to know if is it possible to display a custom tnt countdown using the LunarClient BukkitApi ? The only documentation I found about the BukkitApi is the README but it contains not many things. And also how i can guess mods name like tnt countdown (for the ModSetting) ?

Have a nice day,

**Comment by LaserSlime** [comment]
The id for tnt countdown is "tntCountdown".

**Comment by BebeDlaStreat** [comment]
thx
