### ISSUE TITLE
Lunar Cosmetics and Nametags aren't working with "online mode: false"

### ISSUE THREAD

**Issue by freddycor** [LunarClient/BukkitAPI#46]
Hi, I'm trying to make Lunar Client working with my server.

I have a problem: Nametag's Lunar icon and Cosmetics aren't showing on my server

If the server is set in online mode, then it works all as intended, I can see al players Lunar icon and cosmetics

If the server is in offline mode (which is the one I need) all the lunar tags and cosmetics are gone. I've seen much servers in offline mode that work with Lunar without problems. Also, I can't set on the auth plugin "premiumUUIDs" because if I set like that when a player goes /premium it will see his stats fully reset (can't find a solution to that).
I'm on Spigot1.8.8 and unfortunately I can't change it

Am I missing something? Is there a way to fix it?

Thanks in advance

**Comment by ThatKawaiiSam** [comment]
This is an issue that occurs on all offline Multiplayer servers that do not send legitimate player UUIDs for premium accounts. Unfortunately, there is nothing we can do to support this.
