### ISSUE TITLE
Sending notifications through the API

### ISSUE THREAD

**Issue by CaledonianEH** [LunarClient/BukkitAPI#6]
I'm wondering how to correctly send notifications using the LunarClient API. I've attached my code below, which doesn't currently work, though other packets are functional (such as mods or titles). My best assumption is that I'm using the wrong level, but I don't really know which ones are correct. 

` api.sendPacket(p, new LCPacketNotification("testing", 40, "INFO"));
                        api.sendPacket(p, new LCPacketNotification("testing", 40, "ERROR"));`

**Comment by KevstahJr** [comment]
Didn't they remove notifications after they changed the old Cheatbreaker based 1.7.10 version?

**Comment by bernie-g** [comment]
@CaledonianEH @KevstahJr Notifications aren't currently supported in the client sorry.

**Comment by CaledonianEH** [comment]
Are there any planned updates with the api, such as notifications, or server rules, being able to set the server name so friends can see it on the friends list, or at least documenting the api? I think I can speak for all developers here, we all want new features to improve the servers, and further support other clients. It would highly encourage players to use your client over others, not only for just partners, but almost every server willing to spend the time.

**Comment by colinmcdonald22** [comment]
Hi @CaledonianEH,

We're definitely aware of the lack of documentation here, and plan to address it in an upcoming revamp of the server API. Good LC <-> server integrations benefit everyone, and we're planning on opening that up even more in the near future.
