### ISSUE TITLE
Server Rules / Staff Mods

### ISSUE THREAD

**Issue by Tomoli75** [LunarClient/BukkitAPI#8]
There's not a significant amount of detail surrounding server rules and staff mods, though they appear to be very nice features of Lunar.
Could somebody please provide a list of the possible server rules, as there's no such list within the source code, as well as explaining whether the staff mods are still present in newer versions?
Thanks!

**Comment by PrestigePvP** [comment]
`     MINIMAP_STATUS("minimapStatus", String.class),` **Not supported/Not implemented.**
`    SERVER_HANDLES_WAYPOINTS("serverHandlesWaypoints", Boolean.class),` 
`    COMPETITIVE_GAME("competitiveGame", Boolean.class),` **Not supported/Not implemented.**
`    SHADERS_DISABLED("shadersDisabled", Boolean.class),`
`    LEGACY_ENCHANTING("legacyEnchanting", Boolean.class),`
`    VOICE_ENABLED("voiceEnabled", Boolean.class),` **Not supported/Not implemented.**
`    LEGACY_COMBAT("legacyCombat", Boolean.class);`
